AWSTemplateFormatVersion: "2010-09-09"
Description: VPC in North Virginia for Udagram in Udacity Cloud DevOps Engineer
Resources:
    UdagramVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: "10.0.0.0/16"
            InstanceTenancy: default
            Tag:
                - Key: Name
                  Value: Udagram
                
                    