AWSTemplateFormatVersion: "2010-09-09"
Description: VPC in North Virginia for Udagram in Udacity Cloud DevOps Engineer
Resources:
    UdagramVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: "10.0.0.0/16"
            InstanceTenancy: default
            Tags:
             -  Key: Name
                Value: Udagram
    UdagramPubSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: us-east-1a
            CidrBlock: "10.0.0.0/17"
            Tags:
             -  Key: Name
                Value: public1
            VpcId: !Ref UdagramVPC
    UdagramPubSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: us-east-1b
            CidrBlock: "10.0.0.1/17"
            Tags:
             -  Key: Name
                Value: public2
            VpcId: !Ref UdagramVPC
    UdagramRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref UdagramVPC
    RouteTableAssociation1:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref UdagramRouteTable
            SubnetId: !Ref UdagramPubSubnet1
    InternetGateway:
        Type: AWS::EC2::InternetGateway
    GatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref UdagramVPC
    DefaultRoute:
        Type: AWS::EC2::Route
        DependsOn: GatewayAttachment
        Properties:
            DestinationCidrBlock : "0.0.0.0/0"
            GatewayId: !Ref InternetGateway
            RouteTableId: RouteTable
                    