AWSTemplateFormatVersion: "2010-09-09"
Description: VPC in North Virginia for Udagram in Udacity Cloud DevOps Engineer
Resources:
    UdagramVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: "10.0.0.0/16"
            InstanceTenancy: default
            Tags:
             -  Key: Name
                Value: Udagram
    UdagramPubSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: us-east-1a
            CidrBlock: "10.0.0.0/17"
            Tags:
             -  Key: Name
                Value: public1
            VpcId: !Ref UdagramVPC
    UdagramPubSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: us-east-1b
            CidrBlock: "10.0.0.1/17"
            Tags:
             -  Key: Name
                Value: public2
            VpcId: !Ref UdagramVPC
                
                    